# Nom de l'application
spring.application.name=gestistock-backend

# Indique à Spring de toujours initialiser la base au démarrage
spring.sql.init.mode=always

# Connexion à la base
spring.datasource.url=jdbc:mysql://localhost:3306/gestistock_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Driver de communication
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect